create extension if not exists postgis with schema extensions;

create table if not exists artist (
  id integer generated by default as identity primary key,
  subid varchar(21) not null,
  name varchar(20) not null,
  email varchar(40),
  isadmin boolean not null default false,
  creationdate timestamp without time zone not null default now(),
  privateprofile boolean not null default false,
  notificationsenabled integer not null default 63
);

create table if not exists gif (
  id integer generated by default as identity primary key,
  fps integer
);

create table if not exists art (
  id integer generated by default as identity primary key,
  title varchar(255),
  ispublic boolean not null default false,
  creationdate timestamp without time zone not null default now(),
  isgif boolean not null default false,
  gifid integer not null default 0,
  gifframenum integer not null default 0,
  pointid integer not null default 0,
  width integer,
  height integer,
  encode text
);

create table if not exists likes (
  artistid integer not null references artist(id) on delete cascade,
  artid integer not null references art(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  viewed integer not null default 0,
  primary key (artistid, artid)
);

create table if not exists dislikes (
  artistid integer not null references artist(id) on delete cascade,
  artid integer not null references art(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  viewed integer not null default 0,
  primary key (artistid, artid)
);

create table if not exists contributingartists (
  artistid integer not null references artist(id) on delete cascade,
  artid integer not null references art(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  primary key (artistid, artid)
);

create table if not exists comment (
  id integer generated by default as identity primary key,
  artistid integer references artist(id) on delete cascade,
  artid integer references art(id) on delete cascade,
  replyid integer references comment(id) on delete cascade,
  message varchar(2222),
  creationdate timestamp without time zone not null default now(),
  viewed integer not null default 0
);

create table if not exists commentdislikes (
  artistid integer not null references artist(id) on delete cascade,
  commentid integer not null references comment(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  viewed integer not null default 0,
  primary key (artistid, commentid)
);

create table if not exists commentlikes (
  artistid integer not null references artist(id) on delete cascade,
  commentid integer not null references comment(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  viewed integer not null default 0,
  primary key (artistid, commentid)
);

create table if not exists friends (
  friend1id integer not null references artist(id) on delete cascade,
  friend2id integer not null references artist(id) on delete cascade,
  friend1name varchar(20),
  friend2name varchar(20),
  friendsondate date not null default current_date,
  primary key (friend1id, friend2id)
);

create table if not exists tag (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  creationdate timestamp without time zone not null default now()
);

create table if not exists arttags (
  artid integer not null references art(id) on delete cascade,
  tagid integer not null references tag(id) on delete cascade,
  creationdate timestamp without time zone not null default now(),
  primary key (artid, tagid)
);

create table if not exists artspace (
  artspaceid integer primary key,
  title varchar(255),
  shape extensions.geometry
);

create table if not exists points (
  pointid integer generated by default as identity primary key,
  latitude decimal(9, 6),
  longitude decimal(9, 6),
  artspaceid integer references artspace(artspaceid) on delete cascade,
  title varchar(255)
);

insert into artist (id, subid, name, email, isadmin, creationdate)
values (0, '30595057885342489459', 'Public Grid', 'test@email.com', false, now())
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('artist', 'id'), greatest((select max(id) from artist), 1));

create or replace function delete_art_without_contributors()
returns trigger
language plpgsql
as $$
begin
  delete from art
  where id not in (select artid from contributingartists where artid is not null)
    and gifframenum <= 1;
  return null;
end;
$$;

drop trigger if exists contributingartist_delete_trigger on contributingartists;
create trigger contributingartist_delete_trigger
after delete on contributingartists
for each statement execute function delete_art_without_contributors();

create or replace function delete_orphaned_gif_frames()
returns trigger
language plpgsql
as $$
begin
  delete from art a
  where a.gifid in (
    select old_rows.gifid
    from old_rows
    where old_rows.gifid <> 0
  )
  and not exists (
    select 1
    from art remaining
    where remaining.gifid = a.gifid
      and remaining.gifframenum = 1
  );
  return null;
end;
$$;

drop trigger if exists gif_delete_trigger on art;
create trigger gif_delete_trigger
after delete on art
referencing old table as old_rows
for each statement execute function delete_orphaned_gif_frames();
